htapp/models.py
import datetime

from .ext import db
from .util import enc_pwd

class User(db.Model):
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    name = db.Column(
        db.String(30),
        nullable=True
    )
    email = db.Column(
        db.String(30),
        unique=True,
        index=True
    )
    pwd = db.Column(
        db.String(255),
        nullable=False
    )
    is_active = db.Column(
        db.Boolean,
        default=False
    )
    is_delete = db.Column(
        db.Boolean,
        default=False
    )
    # orders = db.relationship(
    #     'Order',
    #     backref = 'user',
    #     lazy = True
    # )

    @classmethod
    def creat_user(cls,email, pwd,name=None):
#         email 能不能搜到一个用户 检查email
        users = User.query.filter(User.email==email)
        if users.count() > 0:
            return None
            # raise Exception("该Email以被使用")
#         加密密码
        user_pwd = enc_pwd(pwd)
#     创建用户
        name = name if name else email
        user = cls(
            name=name,
            email=email,
            pwd=user_pwd
        )
        db.session.add(user)
        db.session.commit()
        return user

    # 设置密码
    def set_pwd(self, pwd):
        if not pwd or len(pwd) == 0:
            raise Exception("密码不能为空")
        # 先对密码进行加密 再赋值
        self.pwd = enc_pwd(pwd)
        # 保存到数据库
        db.session.add(self)
        db.session.commit()
        return True
    def check_pwd(self,pwd):
        u_pwd = enc_pwd(pwd)
        if u_pwd == self.pwd:
            return  True
        else:

            return False

class Goods(db.Model):
    __tablename__ = "axf_goods"
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    productid = db.Column(
        db.String(20)
    )
    productimg = db.Column(
        db.String(255)
    )
    productname = db.Column(
        db.String(130),
        nullable=True
    )
    productlongname = db.Column(
        db.String(190)
    )
    isxf = db.Column(
        db.Boolean,
        default=False
    )
    pmdesc = db.Column(
        db.Boolean,
        default=False
    )
    specifics = db.Column(
        db.String(40)
    )
    price = db.Column(
        db.Float
    )
    marketprice = db.Column(
        db.Float
    )
    categoryid = db.Column(
        db.Integer
    )
    childcid = db.Column(
        db.Integer
    )
    childcidname = db.Column(
        db.String(30)
    )
    dealerid = db.Column(
        db.String(30)
    )
    storenums = db.Column(
        db.Integer
    )
    productnum = db.Column(
        db.Integer
    )
    order_item_goods = db.relationship(
        'OrderItem',
        backref = 'goods',
        lazy = True
    )
class Order(db.Model):
    __tablename__ = 'axf_order'
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True

    )
    user_id = db.Column(
        db.Integer,
        # db.ForeignKey('axf_myuser.id')
    )
    create_time = db.Column(
        db.DateTime,
        default=datetime.datetime.now
    )
    status = db.Column(
        db.Integer
    )
    order_items = db.relationship(
        'OrderItem',
        backref = 'order',
        lazy = True
    )
class OrderItem(db.Model):
    __tablename__ = 'axf_orderitem'
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    order_id = db.Column(
        db.Integer,
        db.ForeignKey('axf_order.id')
    )
    goods_id = db.Column(
        db.Integer,
        db.ForeignKey('axf_goods.id')

    )
    num = db.Column(
        db.Integer
    )
    buy_money = db.Column(
        db.Numeric(precision=10,scale=2)
    )



htapp/__init__.py
from flask import Flask
# from htapp import settings
from htapp.settings import config
from htapp.ext import init_ext
from htapp.urls_apis import init_api
from htapp.views import init_blue

def create_app(env):
    app = Flask(__name__)

    app.config.from_object(settings.config.get(env))

    init_ext(app)
    init_api(app)

    init_blue(app)

    return app

htapp/views.py
from flask import Blueprint, render_template, request, jsonify
from .models import *
blue = Blueprint("axfbg", __name__)

def init_blue(app):
    app.register_blueprint(blue)


# 写一些视图函数
@blue.route("/")
def item_view():


    page = request.args.get('page',1)
    pagination = Goods.query.paginate(int(page),10)




    return render_template("item/item.html",pagination=pagination,goods= pagination.items)
@blue.route('/item_serch')
def item_serch():

    kw = request.args.get('kw')
    pagination = Goods.query.filter(Goods.productlongname.like("%"+kw+"%")).paginate(1,10)
    return render_template('item/item.html',pagination=pagination,kw=kw,goods = pagination.items)


@blue.route("/order_manage")
def order_manage():
    stutas_map = {
        1:"待付款",
        2:"已付款",
        3:"已发货",
        4: "已收货",
        5:"待评价",
        6:"已评价"
    }


    page = request.args.get('page', 1)
    pagination = Order.query.paginate(int(page), 2)


    for i in pagination.items:
        i.created_time = i.create_time.strftime('%y年%m月%d日 %H:%M:%S')
        i.sum_money = 0
        for j in i.order_items:
            sum_money = i.sum_money +j.num*j.buy_money
        i.sum_money = sum_money
        i.ch_status = stutas_map.get(i.status)






    return render_template("order/order_index.html",pagination=pagination, data=pagination.items)

@blue.route("/nosale")
def nosale():

    return render_template("nosale/nosale.html")


@blue.route("/auto_bh")
def auto_bh():
    return render_template("auto/auto.html")

@blue.route("/indf",methods=['GET','POST'])
def index():
    if request.method == 'GET':
      return render_template("index/index.html")
    if request.method == 'POST':
        par =request.form
        email = par.get('email')
        pwd = par.get('pwd')
        if not all([email, pwd]):
            data = {

                "code": 2,
                "msg": "账号或密码不能为空",
                "data": ""
            }

        return jsonify (data)
    # users = User.query.filter(User.email == email)
    # if users:
    #     if







@blue.route("/register")
def register_view():
    return render_template("register/register.html")

htapp/templates/active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活</title>
</head>
<body>
<h2>欢迎注册爱鲜蜂，请点击下面的连接，激活你的账号，即可体验美女荷官，在线发牌</h2>
 <a href="{{ url }}">{{ url }}</a>

</body>
</html>

htapp/templates/auto/auto.html
{% extends 'base/base_main.html' %}


{% block js %}
    {{ super() }}
    <script>
       $("li").removeClass("active");
       $("#auto_li").addClass("active");
    </script>
{% endblock %}

htapp/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>爱鲜蜂后台管理</title>
    {% block css %}
        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    {% endblock %}
</head>
<body>
    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}
</body>
{% block js %}
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{#    <script type="text/javascript" src="{{ url_for('static', filename='js/md5.js') }}"></script>#}
{% endblock %}

</html>

htapp/templates/base/base_main.html
{% extends 'base/base.html' %}

{% block header %}
    <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li id="item_li" class="active"><a href="{{ url_for('axfbg.item_view') }}">商品管理</a></li>
                        <li id="order_li"><a href="{{ url_for('axfbg.order_manage') }}">订单管理</a></li>
                        <li id="nosale_li"><a href="{{ url_for('axfbg.nosale') }}">不动销管理</a></li>
                        <li id="auto_li"><a href="{{ url_for('axfbg.auto_bh') }}">自动补货</a></li>

                    </ul>
                    <form class="navbar-form navbar-left" action="item_serch">
                        <div class="form-group">
                            <input type="text" class="form-control"name="kw" placeholder="请输入商品名字" id="search_kw">
                        </div>
                        <button type="submit" class="btn btn-primary" id="search_btn">搜索</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">我的 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">修改密码</a></li>
                                <li><a href="#">个人资料</a></li>
                                <li><a href="#">设置</a></li>
                                <li><a href="#">退出</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
{% endblock %}

htapp/templates/index/index.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" class="ui" href="http://www.semantic-ui.cn/dist/semantic.min.css">
</head>
{#    <style>#}
{#        #con{#}
{#           #}
{#            background-repeat: no-repeat;#}
{#            background-size: 100% 100% ;#}
{#        }#}
{#    </style>#}
<body>

<div class="container" id="con">
    <div class="ui inverted segment" style="width: 300px;margin: 100px auto;">
    <div class="ui inverted form" >
        <div class="one fields" >
            <div class="field">
                <label>邮箱</label>
                <input placeholder="邮箱" type="email" id="email" name="email">
            </div>
        </div>

        <div class="one fields">
            <div class="field">
                <label>密码</label>
                <input placeholder="密码" type="password" id="pwd" name="pwd">
            </div>
        </div>

        <div class="ui submit button" id="login">登录</div>
        <div class="ui submit button">
            <a href="{{ url_for('axfbg.register_view') }}">注册</a>
        </div>
    </div>
    </div>
</div>




</body>
<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>

htapp/templates/item/item.html
{% extends 'base/base_main.html' %}

{% block content %}
    <table class="table table-hover">
        <tr>
                <td>商品</td>
                <td>id</td>
                <td>编号</td>

                <td>商品名字</td>
                <td>价格</td>
                <td>数量</td>

                <td>状态</td>


            </tr>
        {% for i in goods %}

            <tr>

                <td><img src="{{ i.productimg }}" style="width: 60px;height: 60px"></td>
                <td>{{ i.id }}</td>
                <td>{{ i. productid }}</td>
                <td>{{ i. productlongname }}</td>
                <td>{{ i. price }}</td>
                <td>{{ i.storenums  }}</td>

                <td>
                  <button type="button" i_d="{{ i.id }}" class="btn btn-info">修改</button>

                    <br>
                    <br>
                     <button i_id="{{ i.id }}" class="btn btn-danger delete_btn">删除</button>
                </td>



            </tr>


        {% endfor %}


    </table>
     <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    {% if pagination.has_prev %}
                        <a href="{{ url_for('axfbg.item_view') }}?page={{ pagination.prev_num }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <a href="{{ url_for('axfbg.item_view') }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% endif %}
                </li>
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        {% if page != pagination.page %}
                            <li><a href="{{ url_for('axfbg.item_view') }}?page={{ page }}&per_page=10">{{ page }}</a></li>
                        {% else %}
                            <li class="active"><a
                                    href="{{ url_for('axfbg.item_view') }}?page={{ page }}&per_page=10">{{ page }}<span
                                    class="sr-only">(current)</span></a></li>
                        {% endif %}

{
                    {% endif %}
                {% endfor %}

                <li>
                    {% if pagination.has_next %}
                        <a href="{{ url_for('axfbg.item_view') }}?page={{ pagination.next_num }}&per_page=10" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <a href="{{ url_for('axfbg.item_view') }}?page={{ pagination.pages }}&per_page=10" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>


{% endblock %}


{% block js %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/item.js') }}"></script>
{% endblock %}

htapp/templates/nosale/nosale.html
{% extends 'base/base_main.html' %}


{% block js %}
    {{ super() }}
    <script>
       $("li").removeClass("active");
       $("#nosale_li").addClass("active");
    </script>
{% endblock %}

htapp/templates/order/order_index.html
{% extends 'base/base_main.html' %}


{% block content %}
    <table class="table table-hover">
        <tr>
            <td>用户id</td>
            <td>订单id</td>
            <td>状态</td>
            <td>创建时间</td>
            <td>订单总金额</td>
            <td>商品</td>
            <td>操作</td>
        </tr>
        {% for i in data %}
            <tr>

                <td>{{ i.user_id }}</td>
                <td>{{ i.id }}</td>
                <td class="o_status">{{ i.ch_status }}</td>
                <td>{{ i.create_time }}</td>
                <td>{{ i.sum_money }}</td>
                <td>
                    <ul>
                        {% for j in i.order_items %}
                            <li>{{ j.goods.productlongname }}</li>

                        {% endfor %}

                    </ul>
                </td>
                <td>

                    <select name="" id="" o_id="{{ i.id }}">
                        <option value="1" {{ "selected" if i.status==1 }}>待付款</option>
                        <option value="2" {{ "selected" if i.status==2 }}>已付款</option>
                        <option value="3" {{ "selected" if i.status==3 }}>已发货</option>
                        <option value="4" {{ "selected" if i.status==4 }}>已收货</option>
                        <option value="5" {{ "selected" if i.status==5 }}>待评价</option>
                        <option value="6" {{ "selected" if i.status==6 }}>已评价</option>
                    </select>
                </td>
                {#            <td>{{ i. }}</td>#}
            </tr>

        {% endfor %}


    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                {% if pagination.has_prev %}
                    <a href="{{ url_for('axfbg.order_manage') }}?page={{ pagination.prev_num }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% else %}
                    <a href="{{ url_for('axfbg.order_manage') }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% endif %}
            </li>
            {% for page in pagination.iter_pages() %}
                {% if page %}
                    {% if page != pagination.page %}
                        <li><a href="{{ url_for('axfbg.order_manage') }}?page={{ page }}&per_page=2">{{ page }}</a></li>
                    {% else %}
                        <li class="active"><a
                                href="{{ url_for('axfbg.order_manage') }}?page={{ page }}&per_page=2">{{ page }}<span
                                class="sr-only">(current)</span></a></li>
                    {% endif %}

                    {
                {% endif %}
            {% endfor %}

            <li>
                {% if pagination.has_next %}
                    <a href="{{ url_for('axfbg.order_manage') }}?page={{ pagination.next_num }}&per_page=2"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% else %}
                    <a href="{{ url_for('axfbg.order_manage') }}?page={{ pagination.pages }}&per_page=2"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
            </li>
        </ul>
    </nav>





{% endblock %}
 {% block js %}
    {{ super() }}
{#    清空所有的li的active class#}
    <script>
        $("li").removeClass("active");
        $("#order_li").addClass("active");
    </script>
    <script src="{{ url_for('static', filename='js/order.js') }}"></script>
{% endblock %}

htapp/templates/register/register.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" class="ui" href="http://www.semantic-ui.cn/dist/semantic.min.css">
</head>
{#    <style>#}
{#        #con{#}
{#           #}
{#            background-repeat: no-repeat;#}
{#            background-size: 100% 100% ;#}
{#        }#}
{#    </style>#}
<body>

<div class="container" id="con">
    <div class="ui inverted segment" style="width: 300px;margin: 100px auto;">
    <div class="ui inverted form" >
        <div class="one fields" >
            <div class="field">
                <label>邮箱</label>
                <input placeholder="邮箱" type="email" id="email">
            </div>
        </div>

        <div class="one fields">
            <div class="field">
                <label>密码</label>
                <input placeholder="密码" type="password" id="pwd">
            </div>
        </div>

        <div class="one fields">
            <div class="field">
                <label>确认密码</label>
                <input placeholder="确认密码" type="password" id="pwd">
            </div>
        </div>


        <div class="ui submit button">
            <button>注册</button>
        </div>
    </div>
    </div>
</div>


</body>
<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script type="text/javascript" src="{{ url_for('static', filename='js/md5.js') }}"></script>
 <script type="text/javascript" src="{{ url_for('static', filename='register/js/register.js') }}"></script>
</html>